apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-gamer-mario-v1 # nome da aplicação 
  namespace: argocd 
spec:
  project: default

  source:
    repoURL: https://github.com/fch-bsp/gamer-mario.git
    targetRevision: HEAD
    path: k8s # monitorando de 3 em 3 minutos 
  destination: 
    server: https://kubernetes.default.svc
    namespace: gamer-mario ## tag da aplicação 

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    # automated:
    #   selfHeal: false
    #   prune: false