apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario
  namespace: gamer-mario
spec:
  replicas: 2
  selector:
    matchLabels:
      run: mario
  template:
    metadata:
      labels:
        run: mario
    spec:
      containers:
      - name: mario
        image: nandocloud/mariobrosgamer:latest
        ports:
          - containerPort: 8080
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: 200m
        securityContext:
          allowPrivilegeEscalation: false