apiVersion: v1
kind: Service
metadata:
  name: mario
  labels:
    run: mario
  namespace: gamer-mario
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    run: mario
