apiVersion: v1
kind: Service
metadata:
  name: gamer-mario
  labels:
    run: gamer-mario
  namespace: gamer-mario
spec:
  type: LoadBalancer
  # type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    run: gamer-mario
